ACGN-stock/acgn-stock

README.md

as title.
建議可以使用 issue trace 不然老是翻推文挖 feature or bug 還滿煩的，也方便協作。

add simple readme.md

---

routes.js

as title
有考慮用 yarn 嗎？ 速度會比較快。 然後可能要調整一下npm start

重構 routes.js

---

client/utils/styles.css

調整經理人卡色讓股價顯示較明顯。

---

client/ruleDiscuss/ruleAgendaDetail.html

限制投票者名單高度避免手機使用者無法點選確定。

---

client/company/companyList.js

修正持股比例小於1e-4的卡片樣式錯誤。

---

server/intervalCheck.js

@mrbigmouth 
非常抱歉沒有注意到這個錯誤，
需要再請你幫忙把目前dbEmployees中resigned=true的document改成
employed=true, resigned=false的狀態。

修正員工遣散條件錯誤。

---

server/intervalCheck.js

#138 
若昨天登入的時間是10:00，今天的登入時間是11:00。則兩者的登入的時數會超過24小時

修正未登入天數計算的問題

---

client/company/companyList.html
client/company/companyList.js
server/methods/company.js

股市總覽支援只顯示有訂單的公司。

---

client/.eslintrc
client/utils/pagination.html
client/utils/pagination.js

為 pagination 增加一個換頁表單
使用者可以填入想跳的頁數，直接跳至該頁

pagination 增加換頁表單。

---

server/intervalCheck.js

根據未上線天數調整分紅。

---

server/intervalCheck.js

重送：根據未上線天數調整分紅。

---

client/layout/footer.html
client/layout/footer.js
client/utils/helpers.js
db/users.js
server/intervalCheck.js
server/methods/accounts.js

為了減少金管會通告被忽略的狀況，
在有發給該使用者的新金管通告時，footer 會跳出一則提醒，
將使用者導引至自己的帳號資訊頁面。

加入金管通告的未讀通知

---

routes.js

這應該是目前最後一個地方 import 到 config.{js,json} 了

修正 routes.js 的 config 取得方式

---

integration-test/server/methods/users.test.js
package.json
server/methods/users.js

1. 加入 loginOrRegister, validatePTTAccount, validateBahamutAccount 三個 methods 的測試
2. 重構 validatePTTAccount 與 validateBahamutAccount
3. 修正 loginOrRegister 在驗證未完成取消之後換了密碼再行驗證，會導致 dbValidatingUsers 有重複 username 的 entries，以致無法正確完成驗證程序的問題

加入PTT、巴哈帳號認證之測試並修正 loginOrRegister 註冊換密碼無法認證的問題

---

client/company/companyDetail.html
client/company/companyDetail.js
db/dbEmployees.js
integration-test/server/methods/employee/setEmployeeMessage.test.js
server/methods/employee/setEmployeeMessage.js

新增在職員工留言功能

---

client/ruleDiscuss/ruleAgendaDetail.html
client/ruleDiscuss/ruleAgendaVote.html

在議程資訊與投票頁面加入議程相關討論的連結

---

client/company/editCompany.js
server/methods/product/createProduct.js
tests/mock/mongo.js

產品的產品描述為選擇性填寫，但卻錯誤地被前端的 model validation 與後端 method 的檢查擋下來
這邊修正這個問題

修正產品上架不允許描述為空的問題

---

client/accountInfo/accountInfo.js

在按下放假按鍵時，顯示對話框再次確認才進入渡假模式，以避免不小心誤按

進入渡假模式前增加確認手續

---

server/methods/instantMessage/queryInstantMessage.js

dbLog 的資料結構修改並未同步更新至 queryInstantMessage method，這邊修正這個問題

修正即時訊息無法顯示的問題

---

integration-test/server/foundation.test.js
server/foundation.js
server/intervalCheck.js

1. checkFoundCompany 重新命名為 checkExpiredFoundations
2. 分離出 doOnFoundation{Success,Failure} 分別處理新創成功、失敗
3. 增加對新創成功、失敗的處理過程與截止檢查之測試
4. 使用 SimpleSchema 的 clean 功能在使用 bulk 時填入預設值

重構 server/foundation.js

---

client/accountInfo/accountInfo.html
client/accountInfo/accountInfo.js
server/publications/accounts/accountInfo.js

帳號資訊顯示董事長頭銜。

---

server/imports/utils/publishTotalCount.js
server/publications/accounts/accountAccuseLog.js
server/publications/accounts/accountInfoLog.js
server/publications/accounts/accountInfoTax.js
server/publications/accounts/accountOwnStocks.js
server/publications/accuse/accuseRecord.js
server/publications/arena/arenaLog.js
server/publications/company/companyDirector.js
server/publications/company/companyList.js
server/publications/company/companyLog.js
server/publications/companyArchive/companyArchiveList.js
server/publications/foundation/foundationList.js
server/publications/fscStock/fscOwnStocks.js
server/publications/order/companyOrderExcludeMe.js
server/publications/product/productListByCompany.js
server/publications/product/productListBySeasonId.js

外部無需再另外處理該 observer 的 stop，但仍維持 return value 為該 observer 以提供後續彈性使用

將分頁總個數 observer 的 stop 移至 publishTotalCount 內部處理

---

.meteor/packages
.meteor/versions
client/fscStock/fscStock.js
server/publications/fscStock/fscOwnStocks.js

刪除 已查封公司在金管會持股的顯示

---

client/accountInfo/accountInfo.html
client/advertising/advertising.html
client/advertising/advertising.js
client/utils/styles.css

1. 微調 帳號資訊 > 持股資訊 顯示
2. 調整 廣告中心 在手機端的顯示

持股資訊和廣告中心的顯示調整

---

client/utils/displayLog.js
server/methods/accounts/payTax.js

1. 修正公司無經理人時新經理的就任紀錄顯示問題 #263
2. 修正無法繳稅的問題 #274

進行 dev 中已對 log 完成的修正

---

client/company/companyDetail.html
client/seasonalReport/seasonalReport.html
client/seasonalReport/seasonalReport.js
db/dbCompanies.js
db/dbRankCompanyCapital.js
db/migrate.js
dev-utils/factories.js
server/foundation.js
server/functions/company/updateCompanyGrades.js
server/imports/createOrder.js
server/intervalCheck.js
server/publications/season/rankListBySeasonId.js
server/seasonRankAndTaxes.js

根據 #240 實作以下機制
1. 公司新增資本額欄位
2. 公司資訊增加資本額的顯示
3. 系統釋股賣單成交時，將所得加入資本額而非營利
4. 新增公司資本額評級（根據 #249）
1. 以全部未查封公司資本額的四分位數切分區間，依區間由高至低分為 A, B, C, D 四級
2. 新公司初始評級為 D 級
3. 商業季度結束時將更新此評級
4. 公司資訊新增評級顯示
5. 季度報告新增資本額排名

實作公司資本額機制 (#240)

---

client/utils/displayLog.js
db/migrate.js

1. 改用 $rename 取代原本逐筆進 bulk 的移動操作
2. 新寫法會造成部分舊 log 無 data，故 client 的 displayLog 增加對無 data 的防護

改善 migration version 14 的效能

---

client/company/companyDetail.html
client/company/companyDetail.js
client/utils/displayLog.js
config.js
config.json
db/dbArenaFighters.js
db/dbLog.js
server/arena.js
server/methods/arena/investArenaFigher.js
server/publications/arena/companyArenaInfo.js

1. 當報名公司的總投資額未達一定門檻，將在亂鬥正式開打之前從參賽名單除名
2. 被除名的公司，投資人將會收到原本投資數量的退款
3. config 新增上述參賽投資最小門檻的設定

實作亂鬥報名門檻機制

---

client/announcement/announcement.html
client/announcement/announcement.js
integration-test/server/functions/company/releaseStocksForHighPrice.test.js
server/functions/company/helpers.js
server/functions/company/releaseStocksForHighPrice.js
server/functions/company/updateHighPriceCompanyCount.js
server/functions/company/updateHighPriceThreshold.js
server/functions/company/updateLowPriceThreshold.js
server/intervalCheck.js
server/publications/variables.js

根據此提案決議
https://acgn-stock.com/ruleDiscuss/view/T5byCEJc6nBMMm6yd
https://www.ptt.cc/bbs/ACGN_stock/M.1511929830.A.17E.html

新增高價股價格門檻，以此為高價釋股依據

---

server/paySalaryAndCheckTax.js

根據資本額修正員工營利公式。

---

db/migrate.js

v13（加入最萌亂鬥大賽機制）:
1. 在無賽季或無商業季度的狀況下，不進行大賽資料推導
2. 以最後一個賽季的商業季度數量計算出正確的 arenaCounter 值
v14（log 重構）：
1. 對每個 logType 排除完全沒有資料的狀況，避免在無運算時執行 bulk op
2. 將 bulk op 移至 forEach 外，全部的 logType 修正現在共用一個 bulk op

修正 migraion v13 與 v14

---

client/utils/displayLog.js
db/dbLog.js

1. 修正原本無經理人時就任時不會顯示公司名稱的問題
2. 修改讓 0 股支持的狀況也顯示支持股數

修正就任經理 log

---

client/company/companyDetail.html
server/publications/order/companyOrderExcludeMe.js

公司資訊頁顯示微修正

---

client/layout/tutorial.html
client/layout/tutorial.js
config.js
config.json
integration-test/server/methods/miningMachine/placeStone.test.js
server/methods/miningMachine/placeStone.js

issue #252 中並未提及，但原提案中有此限制並且通過投票

增加聖晶石最多只能使用七顆的限制

---

client/layout/tutorial.html

解決 client/layout/tutorial.html 的 conflict

Merge hotfix into dev

---

client/foundation/foundationDetail.html
client/foundation/foundationDetail.js
client/foundation/foundationList.js
client/utils/methods.js

新創公司的公司資訊新增投資按鍵

---

.meteor/packages
.meteor/versions
client/company/companyDetail.js
client/layout/nav.js
client/seasonalReport/seasonalReport.js
client/utils/globalVariable.js

1. 修正季度報告圖表顯示
2. 使用Reactive-Dict取代session

修正季度報告圖表顯示

---

db/migrate.js
server/startup/accountsOnCreateUserHook.js

1. migration v18 將既存使用者的消費券數量設定為 0
2. 新使用者的消費券數量更改為 0

更改初始狀況的使用者消費券數量

---

server/publications/product/companyMarketingProducts.js

修正玩家買下剩餘產品數量時，在尚有庫存時顯示已完售的問題

---

client/arenaInfo/arenaInfo.html
client/arenaInfo/arenaInfo.js
client/layout/footer.html
client/utils/styles.css

置底廣告顯示修正與亂鬥顯示顯示調整

---

client/company/companyMiningMachinePanel.html
client/company/companyMiningMachinePanel.js
client/utils/displayLog.js
config.js
config.json
db/dbLog.js
db/migrate.js
integration-test/server/methods/miningMachine/placeStone.test.js
integration-test/server/methods/miningMachine/retriveStone.test.js
server/methods/miningMachine/placeStone.js
server/methods/miningMachine/retrieveStone.js
server/publications/miningMachine/companyStones.js

1. logType 移除「礦機放石」與「礦機取石」，並於 migrate 時移除
2. retrieveStone 的 rate limit 回到預設的一分鐘 20 次
3. fix typo
4. 公司資訊的挖礦機資訊增加石頭放置名冊

移除礦機的取石 / 放石 log & 增加石頭放置名冊

---

config.js
config.json

此修改依據 https://acgn-stock.com/ruleDiscuss/view/uP6GcD8te5ui8CGgW 中
「會員等級之分紅加成強化」議題之修改

調整 VIP 分紅加成

---

config.js
config.json

此修改依照 https://acgn-stock.com/ruleDiscuss/view/uP6GcD8te5ui8CGgW 中
「產品最後出清販售之調整」議題之決議

產品最後出清時間調整為 24 小時

---

client/layout/tutorial.html
client/layout/tutorial.js
db/dbCompanies.js
server/functions/company/updateCompanyGrades.js

此修改依照 https://acgn-stock.com/ruleDiscuss/view/uP6GcD8te5ui8CGgW 中
「公司評級增加S等級」議題之決議

增設 S 級公司評級

---

server/functions/company/updateHighPriceThreshold.js

此修改依照 https://acgn-stock.com/ruleDiscuss/view/uP6GcD8te5ui8CGgW 中
「修改高價釋股公司之範圍」的決議。

修改高價釋股公司之範圍

---

db/dbArenaFighters.js
server/arena.js

依照 https://acgn-stock.com/ruleDiscuss/view/GBe2gsij9XCm3PHJ9 的決議進行修改
包含除了「反擊機制」以外的所有內容

亂鬥數值調整與規則調整

---

config.js
config.json
db/dbRound.js
server/methods/foundation/foundCompany.js

依照 https://acgn-stock.com/ruleDiscuss/view/6cnssHsePossL2hmX 之決議

 賽季開頭 60 分鐘禁止新創

---

server/imports/utils/loginObserver.js
tests/units/no_login_day_count.test.js

1. 修正新玩家第一次登入時不一定會有登入紀錄的問題
2. 內部 observer 的 changed 事件中移除不必要的登入時間更新

修正 loginObserver 的 bug & 整理程式碼

---

integration-test/server/functions/company/releaseStocksForNoDeal.test.js
server/functions/company/releaseStocksForNoDeal.js

依照 https://acgn-stock.com/announcement/view/aQ5en7Qj2be3vTwtM 之規劃
新上市公司 24 小時內，低量釋股的門檻提高為「日成交量 + 總釋股數」

實施新上市公司之低量釋股保護機制

---

db/dbViolationCases.js

更新違規舉報的文字樣版

---

client/utils/displayLog.js
db/dbLog.js
server/methods/advertising/addAdvertisingPay.js

由於舊 log 的實際廣告發起人已經丟失，無法準確回復資料
目前只針對新產生的 log 進行修正

廣告競價 log 增加發起人之 userId

---

client/violation/helpers.js
client/violation/violationCaseActionLogDisplay.js
client/violation/violationCaseDetail.js
db/dbViolationCaseActionLogs.js
db/dbViolationCases.js
db/migrate.js
server/methods/violation/setViolationCaseState.js

1. 調整語句，將「已受理」改為「處理中」，並微調部分對應的顯示
2. 承上，將案件狀態 accepted 改為 processing，並微調部分對應的紀錄
3. 調整金管會對案件的處理流程，一律先讓案件進入處理中狀態，再進行結案或駁回
4. 移除 acceptedAt, closedAt, rejectedAt 等未用到的 timestamps

調整違規舉報處理系統

---

client/product/productCard.js

在 #492 中修正了 server 端，但並未修正 client 端。

修正在現金為負數時僅使用消費券仍然無法購買產品的問題

---

client/announcement/announcementDetail.html
db/dbAnnouncements.js

1. 企劃組成員可以發佈營運公告，用以發佈一般營運相關公告使用（e.g., 節慶送禮）
2. 公告內容的標題進行相對應的調整

公告類別新增「營運公告」

---

dev-utils/createSeedData.js

將seed data的公司設定的更完整，方便測試時使用
- 將 user1 設為所有公司的經理人
- 將所有公司的股票隨機分配給所有使用者

修正 createSeedData() 產生的資料

---

client/layout/nav.html

將上欄的 主題配置 改為 設定
減少欄位長度，未來亦可放入其他設定

修改上欄文字 (主題配置 => 設定)

---

client/accountInfo/accountInfo.js
client/company/companyDetail.js
client/foundation/foundationDetail.js
client/mainPage/mainPage.js
client/ruleDiscuss/ruleAgendaDetail.js
client/ruleDiscuss/ruleAgendaVote.js
config.js
config.json
routes.js
server/startup/metaTag/getCompanyMetaTag.js
server/startup/metaTag/getFoundationMetaTag.js
server/startup/metaTag/webMetaTag.js

依照企劃部的提議修改簡介
將股市的資訊寫入config檔
* 將名稱、描述、domain name、預設圖片網址寫入config中的 websiteInfo
* 將原本的 websiteName 移入 websiteInfo 中

修改股市預覽時的預設簡介

---

client/layout/tutorial.js
config.js
config.json
integration-test/server/methods/miningMachine/placeStone.test.js
server/methods/miningMachine/placeStone.js

依照 https://acgn-stock.com/announcement/view/yfnheiJnyPeGGSrFJ 的規劃

移除聖晶石同一人只能使用七顆的限制

---

server/publications/arena/arenaInfo.js

參照 commit 013d8b11fbd878258c91405a0eb1bcf22f6664f9

修正亂鬥攻擊順序經由 ``arenaInfo`` leak 的問題

---

README.md
client/layout/layout.html
client/layout/loading.js
config.js
config.json
package-lock.json
package.json
server/http/robots.js
server/http/sitemap/sitemapCompanies.js
server/http/sitemap/sitemapIndex.js
server/http/sitemap/sitemapMain.js
server/startup/prerender.js
server/startup/prerenderServer.js

Reverts mrbigmouth/acgn-stock#594
復原revert

Revert "Revert "20190303更新""

---

client/company/companyDirectorList.html
client/company/companyList.html
client/foundation/foundationList.html
client/utils/displayLog.html
client/utils/styles.css

修正`company-card`內使用者連結會超出卡面的問題
修正 `董事會留言` 與 `即時訊息` 會被`！`超出顯示範圍的問題

修正部分文字超出顯示範圍的錯誤

---

dev-utils/imports/mongo-scripts/fixDbTimeTool.js

修正價更時間區間沒有改到的問題
修正weekly工作時間推遲太多週數的問題
改為星期五復原時才推遲到下周，否則到這周

修正DB時間修過頭的問題

---

client/layout/nav.js
client/seasonalReport/seasonalReport.js
client/utils/displayLink.js
client/utils/displayLog.js
db/dbAnnouncements.js

放寬系統公告的權限限制，方便發布適當公告
刪除因快取問題而留下的暫時性code

 放寬系統公告的權限限制 & 刪除不必要的code

---

client/layout/footer.html

修正 Bug回報 的連結

---

client/layout/layout.html

加入 Google Analytics 服務
可以統計玩家都從哪裡來、幾點玩之類的

加入 Google Analytics

---

integration-test/server/functions/foundation/doOnFoundationFailure.test.js

使用 rawCollection 操作時，會回傳 Promise
讓 Promise 飛一會

修正 doOnFoundationFailure.test 總是時好時壞的問題

---

client/accountInfo/accountAboutEditForm.js
client/company/companyEditForm.js

在發送更新時如果一開始就沒有圖片，且此次更新也未填上時，將導致送出的資料沒有 picture (pictureSmall, pictureBig) 欄位，並導致後端執行 check 時出錯
即使在後端 check 的數值加上 undefind 亦無效果 ( Match.OneOf(String, null, undefind) )
推測會先確認欄位存不存在才對內容進行確認
因此在前端發送前先將其初始化為 null

在更新 使用者自介 或 公司介紹 時補上空缺的圖片值

---

client/utils/styles.css

增加 user card 的高度限制

---

db/dbUserArchive.js
db/users.js
package-lock.json
server/imports/migrations/047-add-user-archive-about.js
server/imports/migrations/index.js
server/intervalCheck.js
server/startup/accountsOnCreateUserHook.js

讓 `user.about` 的資料在賽寄結束時也會被保存進 `dbUserArchive` ，並在下次啟用帳號後復原

在賽季結束時保存使用者的個人簡介

---

client/layout/tutorial.html
client/mainPage/mainPage.html

change manual to https://hackmd.io/@ACGN-stock/manual
because the bitbook is hard to edit as a team now.

Dev speedypard 20201125
