server/intervalCheck.js

@mrbigmouth 
對不起我當時沒有進到這個修正orz
又要再麻煩您把registerAt早於2017/11/5 10:00:00且resigned=false的資料改為employed=true

修正換季時雇用員工條件錯誤。

---

client/layout/nav.html

原本聖晶石的圖片路徑是相對路徑，在非 root 的頁面顯示會不正常，因此改為絕對路徑

修正聖晶石的圖片路徑。

---

client/utils/pagination.html
client/utils/pagination.js
server/methods/accounts.js
server/methods/accuse.js
server/methods/company.js
server/methods/foundation.js
server/methods/order.js
server/methods/product.js
server/methods/utils.js

試圖解決以下問題：
1. 訂單總量有兩頁，分頁條顯示有兩頁，使用者目前在第一頁
2. 有人撤單使訂單總量下降到不滿一頁，此時分頁條未即時更新，仍然顯示有兩頁
3. 使用者按下分頁條連結進入第二頁
4. 此時分頁條更新，因總量不滿一頁，分頁條會消失不見，因此使用者無法回到第一頁
以下是針對問題進行的更動：
- 分頁條顯示的條件由原來的「超過一頁才顯示」改成「有資料就顯示」
現在只有完全沒資料才會隱藏分頁條，避免有人跳到空頁面之後回不來
- 原本的 ``variables.totalCountOf*`` 在訂閱後會有無法反映全部數量的問題，導致分頁條的總頁數無法即時更新
現在把總量與分頁內容以兩個 cursor 來 observeChanges 分別處理
其他顯示上的更動：
- 補上跳頁表單 input 欄位的 css class
- 公司產品中心的發佈每頁限制 server 端是 10 個，但 client 端是 30 個，以 client 端的 30 為準修改

修改分頁條顯示條件與總數量的發佈 bug

---

client/layout/tutorial.html

董事會分紅計算原本描述是依照持股比例均分，然而在遇到殭屍或是當季未上線到一定程度時，並不能只看對公司總釋股數的比例
因此強調董事會分紅計算為以「個人之持股數量對所有董事的總持股數量之比例」分配
並補充在當季未上線時，個人持股會以 0% 計算

補充分紅計算中對於董事持股數量的描述

---

dev-utils/.eslintrc
dev-utils/createSeedData.js
dev-utils/factories.js
package.json

在開發時會需要建立一些初始資料來幫助測試
若是直接進入 mongo 的 shell 操作，會有點繁複，尤其是當需要將整個資料庫清空重建的時候
``createSeedData`` 可以清空目前資料庫，再依照裡面寫的方式塞進資料
在開發模式進入 ``meteor shell`` 後 import 進來，即可使用 ``createSeedData({ reset: true})`` 來將原來的資料庫清空並建立新的資料
目前只有建立 100 個 users 與 100 個 companies，並指定 user1 為 admin
日後可以依需求再擴增

增加開發時用的 users 與 companies 資料產生機制

---

client/companyArchive/companyArchiveDetail.js
dev-utils/createSeedData.js

在 ``meteor build`` 時 xolvio:cleaner 這個 package 會找不到，估計可能是 dev-only 的 package
目前以手動清除所有 collections 的方式代替 xolvio:cleaner 的 resetDatabase

移除 dev-utils/createSeedData 對 xolvio:cleaner 的引用

---

client/company/companyDetail.html
client/company/editCompany.html
client/company/editCompany.js
client/productCenter/productCenterByCompany.html
client/productCenter/productCenterByCompany.js
client/productCenter/productCenterBySeason.html
client/utils/displayLink.js
db/dbProducts.js
dev-utils/factories.js
server/methods/product/createProduct.js

增加選擇性的「產品描述」欄位，上限 500 字
方便經理人簡介產品內容與解釋產品意涵，而不必全寫在產品名稱的 255 字裡面
一般大眾也能更快速地分別產品標題與介紹
其他修正：
* ``productLink`` template 補上連結的 title，方便當產品名稱過長被 truncate 掉時，滑鼠指上去仍能看得到完整名稱
* 公司的產品中心頁面補上金管會的「下架」按鍵，原本只有在當季的產品中心才有
* 在公司產品中心頁、當季產品中心頁、公司管理頁等等較大空間的頁面，移除產品名稱欄的 ``text-truncate`` 樣式，以讓人能完整閱讀名稱與描述
* 修正一些文字上與排版上的錯誤

增加產品描述欄位 & 產品介面修正、調整

---

client/company/companyDetail.html

儲備員工列表應該一列顯示一個報名的使用者
但出現排版錯誤導致用同行接續的方式顯示一串使用者資料
這邊修正這個問題

修正儲備員工列表的排版問題

---

client/company/companyList.html
client/company/companyList.js
client/companyArchive/companyArchiveList.html
client/companyArchive/companyArchiveList.js
client/foundation/foundationList.html
client/foundation/foundationList.js
server/imports/buildSearchRegExp.js
server/publications/company/companyList.js
server/publications/companyArchive/companyArchiveList.js
server/publications/foundation/foundationList.js

為股市總覽、新創計劃與保管庫的搜尋加上了「模糊比對」的能力
當選擇模糊比對時，輸入的關鍵字比對時將會考慮中間被插入任何字元的狀況
而原本的比對行為現稱為「完全比對」，關鍵字必須一字不差且中間沒有任何其他字元才能 match
使用者可視情況選用適合的比對方式
以實際狀況當例子，角色名稱為 ``U -511(艦これ)``
tags 有 ``艦隊收藏``、``艦隊``、``艦これ``、``kancolle``、``潛艦``、``U -511(艦これ)``
若是選用完全比對，使用者以 ``U-511`` 做為關鍵字搜尋，並無法找到該角色
這時就可以選用模糊比對來增加搜尋範圍
可一定程度減少角色名被插入各種特殊字元時，對原本完全比對的搜尋方式造成的障礙

新增模糊比對搜尋功能

---

client/company/companyDetail.html
tests/mock/mongo.js

1. 在職員工列表應該一列顯示一個報名的使用者
但出現排版錯誤導致用同行接續的方式顯示一串使用者資料與留言
這邊修正這個問題
2. 員工列表過長時，原本應該出現捲軸，現在補上了

修正員工列表的排版問題

---

client/company/companyList.html
client/company/companyList.js
client/companyArchive/companyArchiveList.html
client/companyArchive/companyArchiveList.js
client/foundation/foundationList.html
client/foundation/foundationList.js

目前頁面跳轉之後再回來的話，公司搜尋欄位的比對方式顯示上會維持在「完全比對」而非目前所選擇的狀態
這邊修正這個問題

修正跳頁之後搜尋比對方式顯示會重置的問題

---

server/intervalCheck.js

解除放假的程式缺少 ``{ multi: true }`` 的 option，無法讓全部已標記解除放假的人解除放假
這邊修正這個問題

修正解除放假模式只更新到一個人的問題

---

client/company/companyDetail.html
client/company/companyDetail.js
client/company/companyList.html
client/foundation/foundationDetail.html
client/foundation/foundationDetail.js
client/foundation/foundationList.html
client/utils/displayLog.js
client/utils/helpers.js
client/utils/styles.css
db/dbCompanies.js
db/dbFoundations.js
server/foundation.js
server/methods/company/markCompanyIllegal.js
server/methods/company/unmarkCompanyIllegal.js
server/methods/foundation/markFoundationIllegal.js
server/methods/foundation/unmarkFoundationIllegal.js
server/publications/company/companyList.js

實作 #261 提到的功能
* 金管會成員可以在公司新創時期或公司上市後，設定該公司的違規標記，最多十個字
* 違規標記設定後，會在公司(新創)列表或該公司的資訊頁顯示標記原因
* 公司在新創時期的違規標記，在該公司上市時仍會留存著
* 金管會成員可以隨時解除違規標記

增加金管會對新創或上市公司標記違規的能力

---

client/arenaInfo/arenaInfo.js
client/company/companyDetail.html
client/company/companyDetail.js
client/layout/tutorial.html
config.js
config.json
db/dbArenaLog.js
db/migrate.js
server/arena.js
server/publications/arena/arenaLog.js

1.優化最萌亂鬥大賽的戰鬥紀錄存取機制，並將最大戰鬥回合數增加到1000回合。
2.經理人決策增加隨機排序按鈕。
3.增加擊倒獎勵。
4.增加排名獎勵。

最萌亂鬥大賽規則調整

---

client/utils/displayLog.js
server/methods/accuse/takeDownProduct.js

原本記的是產品 ID，但下架刪除後就無法以該 ID 找到產品資訊
因此需要另外記錄（比照新創失敗的解法）

修正產品下架 log 沒有記到產品名稱的問題

---

server/arena.js

1. 當只有一人參賽時，仍然完整跑完整個大賽流程
2. 大賽排名獎金補上缺少的 0.177 常數項

修正亂鬥大賽排名獎金與只有一人參賽時的運算

---

.eslintrc

``eslint-plugin-meteor`` 的 ``eventmap-params`` 規則遇到 object spread 時會 crash
因為此規則似乎只能檢查 ``Template.xxx.events`` call 中 object literal 的 function 參數名稱
以其他 mixin 方式來寫，無法被這個規則檢查到，所以決定直接停用此規則

關閉 meteor/eventmap-params 規則，避免 eslint crash

---

client/accountInfo/accountInfo.html
client/accountInfo/accountInfo.js
client/accountInfo/accountInfoOwnStockList.js
client/accountInfo/accountInfoOwnedProductsPanel.js
client/accountInfo/accountInfoStonePanel.js
client/accountInfo/accountInfoTaxList.js
client/accountInfo/accountLogViewer.js
client/accountInfo/helpers.js

1. 將 lookUser 提升至 helpers，並改名為 paramUser
2. 以 paramUser 與 paramUserId 取代取得目前頁面 userId 與 user 的邏輯
3. 以 paramUser 與 paramUserId 取代 Template instance data 的 user，新的 panel
不再需要 user 引數
4. 金管會通告對話框將顯示被通告的使用者名稱
5. 與 idle 相關的 autorun 使用 autorunWithIdleSupport 代替

重整帳號資訊相關程式碼

---

dev-utils/imports/mongo-scripts/fix-rankCompanyPrice-profit.js
server/seasonRankAndTaxes.js

1. 修正因產品新制，季度報告計算上沒修改到，而計算結果與排序錯誤的問題
內含一個mongo-script，執行後，會重新計算第一季到上一季的rankCompanyPrice，並覆蓋原本的結果

修正因產品新制，季度報告計算上沒修改到，而計算結果與排序錯誤的問題

---

server/intervalCheck.js

目前董事長檢查是固定間隔，在最後一次檢查至賽季結束前可以進行一些操作，讓賽季結束時的董事長與董事會清單不一致
由於賽季最後的備份會交給博物館使用，此舉將導致博物館看到的資料不正確
因此在賽季結束前需要強制進行一次董事長檢查，以避免上述問題

在賽季結束時檢查所有公司董事長，避免出現與公司董事清單不一致的狀況

---

client/utils/helpers.js
client/utils/styles.css

將Markdown產生之<code>區塊內的跳脫字元反跳脫回來以使顯示正常化
調整引用的左內縮程度、拔除右內縮，以優化手機顯示效果

Markdown顯示效果修正

---

client/accountInfo/accountInfo.html
client/accountInfo/accountInfo.js
client/accountInfo/accountInfoManageRolePanel.html
client/accountInfo/accountInfoManageRolePanel.js
client/utils/displayLog.js
common/imports/guards/companyGuard.js
db/dbLog.js
db/users.js
integration-test/server/methods/product/createProduct.test.js
server/methods/accounts/assignUserRole.js
server/methods/accounts/unassignUserRole.js
server/methods/company/editCompany.js
server/methods/company/updateProfitDistribution.js
server/methods/product/createProduct.js
server/methods/product/removeProduct.js

1. 帳號資訊中加入了身份組管理區塊，在使甩者有權限可以管理時會顯示
* 超級管理員：可管理所有除自身以外的身份組
* 營運總管：可管理企劃部成員、工程部成員、金管會成員
2. 加入身份組指派 / 解除時的 log 顯示
3. fix typo: managable -> manageable
4. 帳號資訊中顯示使用者識別碼，方便進行 copy

加入基礎的身份組管理功能

---

client/foundation/foundationDetail.js

改為以投資額做反向 stable sort，而非對投資額正向 sort 再反轉，以維持投資的實際先後次序

修正新創投資團隊的排序方式

---

client/utils/displayLink.js

此修正加入 userLink template 對 `Template.currentData()` 的更新偵測，
如此一來在 template instance 被系統重用，資料因此更新時，才會顯示正確的資料。
此修正也同時解決新創計劃投資團隊因名單變動造成的顯示錯誤。

 修正在某些頁面切換時，玩家連結會突然消失或顯示錯誤的問題 

---

server/intervalCheck.js

前面已經將非金管會相關的所有紀錄移除了，無需再特別移除帶有公司 ID 資訊的紀錄。

修正金管會相關紀錄中有帶公司 ID 的紀錄在換賽季時會丟失的問題

---

client/accountInfo/accountInfoTaxList.html
client/accountInfo/accountInfoTaxList.js
client/utils/displayLog.js
db/dbLog.js
db/dbTaxes.js
dev-utils/createSeedData.js
dev-utils/factories.js
server/imports/migrations/032-tax-separate.js
server/imports/migrations/index.js
server/methods/accounts/payTax.js
server/paySalaryAndCheckTax.js
server/seasonRankAndTaxes.js

依照 https://acgn-stock.com/announcement/view/L9HsZTEKYPSbaSjj8 之規劃
實作新稅制系統(現金股票分離課稅)
原資產稅分裂為 股票資產稅 與 現金資產稅
1. 修改 generateNoStockUserWealthList() 的輸出，增加 money 的項目，以利後續使用
2. 將稅金計算函式獨立成 computeTax() 方便查表算稅金
3. tax 分為 stockTax 與 moneyTax
4. 因應前項改動，逾期繳稅罰金由 tax的10% 改為 (stockTax + moneyTax)的10%
4. 捨棄log中的assetTax，新增stockTax與moneyTax
5. tax中的 zombie 改為 zombieTax
6. 將 dbTaxes 中誤植的 min: 1 改為 min: 0
7. 改變 accountInfoTaxList 的table排版方式，使其可以配合內容調整長度

實作新稅制系統(現金股票分離課稅)

---

client/utils/pagination.js
server/functions/company/summarizeAndDistributeProfits.js
server/publications/product/productListBySeasonId.js

- 計算分紅時因誤用了錯誤的變數，使得應該只扣1%的員工獎勵金 變成 多扣一次員工分紅(預設為5%)
- 產品中心的訂閱限制因誤用別的名字導致沒有被限制

修正 有員工的公司在計算分紅時多扣錢的問題 與 產品中心未正確限制訂閱次數的問題

---

.gitignore
client/utils/methods.js
config.js
config.json
db/dbCompanies.js
integration-test/server/functions/company/releaseStocksForHighPrice.test.js
integration-test/server/functions/company/releaseStocksForNoDeal.test.js
integration-test/server/methods/order/createBuyOrder.test.js
integration-test/server/methods/order/createSellOrder.test.js
server/functions/company/executeZeroVolumePriceDrop.js
server/functions/company/helpers.js
server/functions/company/releaseStocksForHighPrice.js
server/functions/company/releaseStocksForNoDeal.js
server/methods/order/createBuyOrder.js
server/methods/order/createSellOrder.js

依照 https://acgn-stock.com/announcement/view/s25E8ic86Gse8RnPQ 之規劃
實作股票跌幅限制，對 新創14天內市值低於資本額的公司 實施緩跌機制
1. 重構 `getPriceLimits()` ，計算邏輯分散至 `getPriceUpperLimit()` 與 `getPriceLowerLimit()` ，並將其搬移至 `dbCompanies`，輸入的 `companyData` 除原本要求的 `listPrice` 外，另還需要 `capital`, `totalValue`, `createdAt`
2. 將所有漲跌幅度設定寫入 `config` 中的 `priceLimits`
3. `config` 中增加 `valueLowerThanCapitalCompanyFallLimitTimes` 用來設定創立多少時間內市值過低的公司在跌幅限制內，目前設定第一階段限制時間為新創後 `7天` 內，第二階段限制時間為新創後 `14天` 內
4. 將所有判斷價格上下限的code以 `getPriceLimits()` 取代
5. 在用到 `getPriceLimits()` 的地方，對 `dbCompanies` 取得 `companyData` 時增加輸出 `capital`, `totalValue`, `createdAt` 等欄位，用於計算是否在跌幅限制目標內
6. 新增server端 `createBuyOrder()` 與 `createSellOrder()` 的整合測試
7. 將 vscode 的設定檔加進 `.gitignore`

 實作市值過小時的跌幅限制 (新創低市值緩跌)

---

integration-test/server/functions/employee/autoRegisterEmployees.test.js
integration-test/server/functions/employee/hireEmployees.test.js
integration-test/server/methods/employee/registerEmployee.test.js
server/functions/employee/autoRegisterEmployees.js
server/functions/employee/hireEmployees.js
server/imports/utils/computeActiveUserIds.js
server/intervalCheck.js

依照 https://acgn-stock.com/ruleDiscuss/view/b86GSJQnC58RrYGzd 之議程決議
與　 https://acgn-stock.com/announcement/view/XWD8Y6P2MHvjCkHrt 公告之修正
實作公司打工續任儲備員工 (#368)
1. `generateNewSeason()` 中雇用員工的部分改為調用 `hireEmployees()` 來操作
2. 計算活躍玩家時，不再判斷員工報名
3. `autoRegisterEmployees()` 用於幫活躍玩家報名儲備員工
4. `generateNewSeason()` 於僱用員工後呼叫 `autoRegisterEmployees()`

實作公司打工續任儲備員工 (#368)

---

client/company/companyLogList.html
client/company/companyLogList.js

「只檢視自身紀錄」切換按鍵的監聽事件原為 `click button`，但會與同 template instance 底下的跳頁 button 
的 click 事件衝突，導致按下跳頁時事件同時觸發了「只檢視自身紀錄」按鍵的事件。

修正公司紀錄的跳頁無法正常運作的問題

---

client/accountInfo/accountInfo.html
client/company/companyEditForm.html
client/company/companyList.html
client/foundation/editFoundation.html
client/foundation/foundationList.html
client/layout/nav.html
client/utils/displayLink.html
client/utils/displayLink.js
client/utils/displayLog.js
client/utils/helpers.js
client/utils/populateUserLink.js
client/utils/styles.css

避免玩家無法輕易辨別來自不同認證來源，但名稱卻完全相同的帳號
（e.g., PTT 的 foobar、巴哈姆特的 foobar）
1. 在所有玩家連結以及帳號資訊頁的顯示，加入認證來源的前置字
* PTT 帳號將顯示「PTT」
* 巴哈姆特帳號將顯示「巴哈」
* Google 帳號將顯示「G帳」
2. 調整公司卡片的排版，以配合帳號的認證來源顯示
* 小圖從 100x100 改為 150x150
* 經理人與董事長由小圖右邊移至公司名稱下方
* 其他細部微調
3. 重構 client 端 userInfo 的 ajax 請求處理與顯示流程，將 log 的玩家連結部分與 userLink 樣版共同處合併

使用者名稱顯示時加上認證來源以協助識別

---

server/http/companyInfo.js
server/http/productInfo.js
server/http/userInfo.js

1. `/userInfo` 發佈 Google 帳號玩家資訊時，不再透過 Google API 取得顯示名稱，
一律以 email 作為玩家名稱顯示，避免因自訂名稱造成辨識困難
2. 調整 `/userInfo`、`/productInfo` 與 `/companyInfo`，簡化部分寫法，
在該 id 不存在時以 404 回應而非丟回單純空資料

移除 Google 帳號的名稱顯示 & 重整 ajax 相關的 server 端程式碼

---

client/company/companyList.html
client/foundation/foundationList.html
client/utils/styles.css

1. 修正董事長頭銜的連結錯位問題
2. 將董事長與經理人頭銜放大為一般字型大小
3. 些微調整公司卡片的排版結構寫法，移除用 `small` 元素為基礎的縮排規則，改用 bootstrap 內建的 class 
代替，以減少誤解

修正 & 微調公司卡片的排版

---

client/layout/tutorial.js
config.js
config.json
server/functions/vip/levelDownThresholdUnmetVips.js

依照 https://acgn-stock.com/announcement/view/Z3yRemNrBXsame5YD 之計劃
1. 在低於門檻時，移除機率性掉級的判定，改成必定掉級
2. 進行掉級操作時，由原先的必定只掉一級，改為掉至最低符合門檻之等級

調整 VIP 在換季時的掉級機制

---

server/imports/metaTag/getCompanyMetaTag.js

在公司預覽資料裡的 市值 與 資本額 的資料互相放錯了，將其修正回來

修正公司的 市值 與 資本額 資訊錯置的BUG

---

client/accountInfo/accountInfo.html
client/accountInfo/accountInfo.js
client/company/companyDetailNormalContent.html
client/company/companyList.js
client/company/companyMarketDataPanel.html
client/foundation/foundationDetail.html
client/foundation/foundationList.html
client/foundation/foundationList.js
client/utils/styles.css
db/dbCompanies.js
db/dbFoundations.js
dev-utils/factories.js
integration-test/server/functions/foundation/doOnFoundationFailure.test.js
server/functions/foundation/doOnFoundationFailure.js
server/functions/foundation/doOnFoundationSuccess.js
server/imports/migrations/037-add-company-creator.js
server/imports/migrations/037-add-company-founder.js
server/imports/migrations/index.js
server/methods/foundation/foundCompany.js
server/publications/accounts/accountCreatorTitle.js
server/publications/accounts/accountEmployeeTitle.js
server/publications/accounts/accountFounderTitle.js
server/publications/accounts/accountManagerTitle.js
server/publications/company/companyList.js

1. 新創計劃與公司加入 creator 欄位，以發起該公司新創計劃的人為創立者
2. 修正在新創階段若創立者被解職經理時，在新創失敗時，保證金會因該玩家當下不為經理而不正常歸還的問題
3. 限制頭銜查詢相關訂閱的回傳欄位，以避免不必要的資料傳輸或情報洩漏
4. 調整公司資訊排版，將公司識別碼移至數據資訊區，同時新增創立者顯示
5. 帳號資訊頭銜區新增該玩家的創立公司列表
6. 新創計劃與公司列表卡面新增創立者專屬顏色，其顯示優先度在董事長與經理之下
7. 限制同時進行的新創間數判斷不再以經理為基準，而以創立人為基準，避免解職馬上又復職的操作造成限制無法生效

為新創計劃 / 公司新增創立人欄位，並修正一些問題

---

client/company/companyProductEditForm.html
client/company/companyProductEditForm.js
client/company/editCompanySwitchContentManageProducts.html
client/company/editCompanySwitchContentManageProducts.js
client/layout/tutorial.js
client/product/productCard.html
client/product/productCard.js
client/productCenter/productCenterByCompany.html
client/productCenter/productCenterBySeason.html
client/utils/styles.css
common/imports/utils/schemaHelpers.js
db/dbProducts.js
dev-utils/factories.js
integration-test/server/methods/product/createProduct.test.js
server/functions/product/replenishProducts.js
server/imports/migrations/038-add-creator-to-products.js
server/imports/migrations/039-default-product-replenish-options.js
server/imports/migrations/index.js
server/methods/product/createProduct.js
server/methods/product/editProduct.js
server/publications/product/companyMarketingProducts.js
server/publications/product/productListByCompany.js
server/publications/product/productListBySeasonId.js

待上架產品編輯功能（原 #571）：
1. products 新增 creator, updatedBy 與 updatedAt 欄位，
分別代表產品的建立者、由誰最後更新以及最後更新時間。
若是公司無經理而由金管會代為上架 / 編輯，則以金管會名義記錄
2. migration 時由產品的建立時間 (createdAt) 為準，
找尋在當下時間最近就職的公司經理，以其為該產品之建立者
若當下無經理，表示由金管會代為上架，以金管會為該產品之建立者
3. 微調產品管理頁面，加入建立者、最後更新的顯示，以及已建立的待上架產品編輯支援
4. client 端 tutorial.js 移除不必要的 helpers
5. 調整產品中心的顯示，金管會成員將會看到產品識別碼、建立者與時間、編輯者與時間的情報
實作產品補貨方案擴增：
依照 https://acgn-stock.com/announcement/view/hN4AmgFKsGj3X7rGt 之規劃實作
經理在產品規劃上架時，可選擇「產品補貨基準」與「產品補貨量」兩項設定
在正式開賣後，此設定會影響每次補貨時的數量多寡
產品補貨基準有依照**庫存數**和**總數**兩種
產品補貨量有**極少量**、**少量**、**中量**、**大量**、**極大量**五種
（分別對應原公告的打點滴、細水長流、要射不射、小爆射、大爆射五個方案）
更新前的舊有產品將預設成「極少量」、「庫存數」的設定
其他詳細設定見公告內容
其他更動：
1. 配合本次更動，調整公司當季產品的排版，只有經理人將能看到當初設定的補貨方案
2. 利用 SimpleSchema 內建的驗證機制簡化產品表單驗證輸入部分的邏輯，並微調排版
3. 調整 createProduct 與 editProduct 兩個 method 參數形式
產品資料不再帶 companyId …

 實作待上架產品編輯功能 & 補貨方案擴增 & 其他修正

---

routes.js

將 editCompany 改成和 companyDetail 一致，掛在 companyRoute 底下（即 ``/company/edit/:companyId``）

修正公司經營管理的頁面 path

---

server/imports/metaTag/getCustomMetaTagByPathname.js

重構 getCustomMetaTagByPathname
以switch取代原先陣列比對方式，增進效能

重構 meta tag 判斷路由的部分

---

client/accountInfo/accountInfo.js
client/company/companyDetail.js
client/foundation/foundationDetail.js
client/layout/layout.js
client/ruleDiscuss/ruleAgendaDetail.js
client/ruleDiscuss/ruleAgendaVote.js
routes.js

1. 參考其他網站，將title的呈現方式改為詳細名稱在前，頁面名稱、網站名稱在後，使其可以先呈現較重要的資訊
範例: `中野三玖 - 公司資訊 - ACGN股票交易市場`
2. 重構title的產生方式，統一由 `routes` 的 `getCurrentPageFullTitle()` 產生
3. 補上缺漏的pageNameHash
4. 首頁的title不再特地標註首頁，改為只顯示網站名稱

修改page title的樣式

---

README.md
client/layout/layout.html
client/layout/loading.js
config.js
config.json
package-lock.json
package.json
server/http/robots.js
server/http/sitemap/sitemapCompanies.js
server/http/sitemap/sitemapIndex.js
server/http/sitemap/sitemapMain.js
server/startup/prerender.js
server/startup/prerenderServer.js

- 加入新的package，更新時需要執行 `meteor npm install`
- 有更動config檔
- **需要安裝 `Google Chrome`**
---
加入 `robots.txt` ，讓bot可以讀取，以得知哪些網址我們不建議掃描，還有建議掃描的`sitemap`在哪
加入 `sitemap` ，提供公司網址
網址會依照公司評級指定優先度，評級高的公司會有較高的優先度推薦搜尋引擎抓取 (抓取順序不影響搜尋結果排序)
使用 `prerender` 來讓搜尋引擎的BOT可以抓到完整的頁面
當收到BOT的訪問請求時，會轉由 `prerender server` 代為訪問網站，並將完整的結果傳回去
`prerender server` 監聽的port可以在config中修改，目前port設定為 `3900`
---
由於會開 `prerender server` ，需要在伺服器安裝 `Google Chrome`
可以用這條指令直接安裝
```sh
wget -qO- https://raw.githubusercontent.com/SoftwareSing/linux-install/master/install-chrome.sh | bash
```
安裝後建議重新啟動

SEO -  加入 robots.txt, sitemap, prerender 讓搜尋引擎可以獲取網頁資訊

---

client/accountInfo/accountInfo.js
client/company/companyDetail.js
client/foundation/foundationDetail.js
client/layout/loading.js
client/ruleDiscuss/ruleAgendaDetail.js
client/ruleDiscuss/ruleAgendaVote.js
client/utils/prerenderReady.js
server/startup/prerender.js

1. 將prerender的對象改為只針對搜尋引擎的BOT
社群網站的BOT使用head中的meta tag便足以顯示資訊，且prerender的等待時間太久，可能被社群網站判斷為無法連線
2. 由於一些不確定因素，google拿到網頁時title可能還沒更換完成，但title是搜尋結果顯示的重要依據，因此讓prerender等到title完成更換後才設置ready

只針對搜尋引擎的BOT提供prerender & 讓prerender會等到title變更完成

---

client/accountInfo/accountInfo.js
client/company/companyDetail.js
client/foundation/foundationDetail.js
client/layout/loading.js
client/ruleDiscuss/ruleAgendaDetail.js
client/ruleDiscuss/ruleAgendaVote.js
client/utils/prerenderReady.js
server/startup/prerender.js

Reverts mrbigmouth/acgn-stock#593
復原revert

Revert "Revert "20190303更新""

---

client/company/companyDetailNormalContent.js
client/utils/isHeadlessChrome.js

~~由於沒有`dev` branch，推送到`master`~~
~~`dev`出現了我再修正~~
已修正為推送至`dev`
---
讓BOT可以抓到完整的tag，而非只有前3個
---
~~讓 `綾地寧寧 股票` 關鍵字可以在Google正常運作，而不用特地搜尋 `綾地寧々 股票`~~

在遇到HeadlessChrome時自動開啟所有tag

---

client/layout/footer.html

已有多次玩家反應不知道去哪裡消除該未讀通知，因此在訊息中加註該去頁面中的哪個區塊檢視，希望能降低此類困擾。

調整金管會相關紀錄的未讀訊息文字

---

client/layout/nav.js
client/seasonalReport/seasonalReport.js
client/utils/displayLink.js
client/utils/displayLog.js
db/dbCompanyArchive.js
dev-utils/createSeedData.js
integration-test/server/functions/foundation/doOnFoundationFailure.test.js
integration-test/server/methods/foundation/foundCompany.test.js
server/functions/foundation/doOnFoundationFailure.js
server/functions/foundation/doOnFoundationSuccess.js
server/http/companyInfo.js
server/imports/fixtures/variables.js
server/imports/migrations/043-rename-name-to-companyName-in-companyArchive.js
server/imports/migrations/044-remove-unnecessary-field-in-companyArchive.js
server/imports/migrations/index.js
server/intervalCheck.js
server/methods/company/changeCompanyName.js
server/methods/foundation/foundCompany.js

* 需於賽季更換前更新
* 可能的話建議用測試機測試
---
* 賽季結束時(`doRoundWorks`)，不清空`dbCompanyArchive`以保存公司資料
* 新創失敗時(`doOnFoundationFailure`)，不刪除`dbCompanyArchive`內的資料以保存公司資料
* 新創時(`foundCompany`)，如果有在`dbCompanyArchive`找到`archived`狀態的同名公司，會使用此公司的ID
* 修改公司名稱時(`changeCompanyName`)，如果新名稱有在`dbCompanyArchive`找到`archived`狀態的同名公司，會將其刪除以避免名稱重複，找到其餘狀態的同名公司則會拒絕請求
* `dbCompanyArchive`內的 `name` 改為 `companyName` ，避免與其他DB命名不一致
* 刪除`dbCompanyArchive`內的 `invest` 欄位
---
*測試時如果從`client`檢查結果的話，需注意[companyInfo](https://github.com/mrbigmouth/acgn-stock/blob/master/server/http/companyInfo.js#L36)的快取時間，會讓新創頁面顯示錯誤的連結(可能會連結到companyDetail)
---
commit 99a723e 為一個暫時的方案，因為 `companyInfo` 有一定的快取時間，為避免無法正常顯示網頁才做的，在快取到期後請 Revert 它
或是有什麼選項能直接清空快取?

 [需於賽季更換前更新] 讓同名公司可以繼承ID

---

server/publications/company/companyLog.js
server/publications/violation/violationCaseListSimple.js

讓公司的log與違規案件不會顯示到上一賽季的
---
本來想在log加roundId的，後來發現 `createdAt: { $gt: ... }` 好像沒有拖累很多效能，就直接用 createdAt 來過濾了
加 `createdAt: { $gt: ... }` 後 `executionTimeMillis` 從 16 增加到 17 (7461筆log)
有指定 userId 的話則是從 33 增加到 47 (343筆log)

讓公司的log與違規案件不會顯示到上一賽季的

---

dev-utils/imports/mongo-scripts/fixDbTimeTool.js

伺服器長時間斷線後，可以用此工具修復DB時間
修正包含
* db.eventSchedules
a. 經理選舉 (season.electManager)
b. 萌戰報名封關 (arena.joinEnded)
c. 產品最後出清時間 (product.finalSale)
d. 每日事件（發薪） (global.daily)
e. 高釋 (company.releaseStocksForHighPrice)
f. 低量 (company.releaseStocksForNoDeal)
g. 價更時間 (company.recordListPrice)
h. 換董事長時間 (company.checkChairman)
i. VIP等級更新時間 (vip.checkVipLevels)
* db.variables 的
releaseStocksForNoDealBegin
releaseStocksForNoDealEnd
releaseStocksForHighPriceBegin
releaseStocksForHighPriceEnd
* db.arena 最後一項的
endDate
joinEndDate
* db.season 的 endDate
* 所有人的登入時間 (db.users 的 status.lastLogin.date 欄位)
* 所有稅單的過期時間 (db.taxes 的 exprireDate 欄位)
* 所有新創公司的開始時間 (db.foundations 的 createdAt 欄位)
---
上次長時間斷線時，也修正了 `arenaCounter` ，但我不太確定這是否必要?
看起來 `arenaCounter` 是跟著換季時跑的，在換季時間已經有調整的情況下，需要動此數值嗎?

 長時間休市的DB時間修復工具

---

dev-utils/imports/mongo-scripts/fixDbTimeTool.js

修正因為DB格式不一致導致的錯誤
// 之後應修正Accounts.createUser的格式問題........

修正 fixDbTimeTool 中對 user 的判斷

---

client/layout/layout.html
client/layout/layout.js
client/utils/googleAnalytics/updatePathToGA.js
config.js
config.json

SPA網頁切換頁面時，必須自行將紀錄發給GA才會記錄
---
分開不同環境使用的 GA Tracking ID ，避免開發時的流量被記錄至GA
**production 請將 config 中的 google.analytics 的值改為 UA-143586675-1**
如下
```json
"google": {
"analytics": "UA-143586675-1"
},
```
---
使用 Headless Chrome 爬取網站資料時，不將資料收集至GA

改進 Google Analytics 追蹤 - 紀錄切換的頁面、分開 prod & dev 的 Tracking ID 、不紀錄 Headless Chrome 帶來的流量

---

server/publications/violation/violationCaseDetail.js

修正 #639 提到的BUG
更新的動作 fields 不一定會有全部的欄位出現，因此用刪除的方式取代用空字串覆蓋，避免原本前端有的資料被空字串覆蓋

修正舉報人增加說明後，前端 informer 會被暫時清空的BUG

---

client/advertising/advertising.html
client/layout/footer.html
client/layout/footer.js
client/layout/nav.html
client/mainPage/mainPage.html
client/mainPage/mainPage.js

- 將 `currentRound` 與 `currentSeason` 在前端的訂閱從 `legacyAnnouncement` 移至 `systemStatusPanel`
- 將 `伺服器連線數量` 從下方列移除，改至首頁 `systemStatusPanel` 顯示，並微調底下公告各項時間等資訊的排版
- 將 `BUG回報` 從下方列移除，改至上方 `其他資訊` 下拉選單中
- 廣告顯示改由下方列顯示，將從可以顯示的廣告隨機挑選一個來顯示，並設有高度限制 `50px`

將廣告移至最底部並只隨機顯示一個

---

server/publications/foundation/foundationDataForEdit.js

在編輯新創頁面如果沒有給公司名會造成前端錯誤
(由於js執行順序無法確定，並非任何時候都能重現BUG)

修正編輯新創頁面訂閱的資料內容
